### ISSUE TITLE
Usage guidance

### ISSUE THREAD

**Issue by djjudas21** [autarch/Database-Migrator#7]
Hi there, I'm trying to implement `Database::Migrator` as a component of an existing Perl project. I've got the simple example working with more-or-less the example from the docs:

```perl
#!/usr/bin/env perl
use strict;
use warnings;
use Database::Migrator::mysql;
Database::Migrator::mysql->new_with_options()->create_or_update_database();
```

However I'm struggling to understand how to follow your advice: _"You can simplify this by subclassing the implementation class"_. I'm quite comfortable with Perl as a language but much more hazy on classes/packages and the more application side of things. Please could you say a few words and give an example of how I could implement this effectively as a sub I can call from my main application? My end goal is really to have the application check for database compatibility on startup and invite the user to upgrade the schema if necessary.

Thanks,
Jonathan

**Comment by oschwald** [comment]
We no longer use this library and it isn't actively maintained. I'd suggest looking at something like [Sqitch](https://sqitch.org/).
